services:
  webapp-bind:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - APP_NAME=Bind_Mount_App
